server:
  port: 8088
spring:
  application:
    name: gateway
  config:
    import: optional:configserver:http://localhost:8888
  sleuth:
    reactor:
      instrumentation-type: decorate_on_each
    sampler:
      probability: 1.0
    baggage:
      remote-fields: CURRENT_USER
  zipkin:
    enabled: false

  cloud:
    gateway:
      routes:
        - id: order
          uri: lb://order
          predicates:
            - Path=/v1/orders/**
          filters:
            - CircuitBreaker=order
        - id: user
          uri: lb://user
          predicates:
            - Path=/v1/users/**
          filters:
            - CircuitBreaker=user
        - id: product
          uri: lb://product
          predicates:
            - Path=/v1/products/**,/v1/inventories/**
          filters:
            - CircuitBreaker=product
      default-filters:
        - name: CircuitBreaker
          args:
            fallbackUri: forward:/fallback
resilience4j:
  timelimiter:
    configs:
      default:
        timeout-duration: 2s
